import {ProductProvider} from '../context/ProductContext';
import {CartProvider} from '@/context/cartcontext/page';
import {Geist, Geist_Mono} from 'next/font/google';
import '../globals.css';
import Header from './Header/page'; // Import Header Component
import Footer from './Footer/page';
import Navbar from './navbar/page';
import CustomProvider from '../wrapper';
import {ABeeZee} from '@next/font/google';

const abeezee = ABeeZee({
  subsets: ['latin'],
  weight: ['400'],
  style: ['normal', 'italic'],
  display: 'swap'
});

// Import Navbar Component

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({children}) {
  return (
    <html lang='en' className='overflow-x-hidden max-w-[1440px] flex mx-auto'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${abeezee.className}  flex mx-auto flex-col  overflow-x-hidden  antialiased`}>
        <CustomProvider>
          <ProductProvider>
            <CartProvider>
              {/* Header and Navbar */}
              <Header />
              <Navbar />

              {/* Main Content */}
              {children}

              {/* Footer */}
              <Footer />
            </CartProvider>
          </ProductProvider>
        </CustomProvider>
      </body>
    </html>
  );
}
